processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 500

  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  logging:
    loglevel: "info"

  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true
      
  # Add Dynatrace exporter for your environment
  otlphttp:
    endpoint: "https://TODO.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token TODO"
    tls:
      insecure: false

  # For metrics
  dynatrace:
    endpoint: "https://TODO.live.dynatrace.com/api/v2/metrics/ingest"
    api_token: "TODO"
    default_dimensions:
      deployment.environment: "test"
      service.name: "solace-broker"

receivers:
  otlp:
    protocols:
      grpc:

  solace:
    broker: [solbroker:5672]
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: trace
        password: trace
    queue: queue://#telemetry-trace
    tls:
      insecure: true
      insecure_skip_verify: true


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [solace, otlp]
      #processors: [batch, memory_limiter]
      #exporters: [otlp/jaeger, logging]
      processors: [batch]
      exporters: [otlphttp,otlp/jaeger,logging]
